// core-architecture-wave3 FR-5: `contract/common.ts` is the read-only source of
// truth for the error-code vocabulary, so ONE of the two sides has to be
// generated and the other checked. This is the generated side: the union's
// members are parsed out of the TS at compile time and emitted as a plain
// `&[&str]`. `ipc::ErrorCode` is the checked side — a `#[cfg(test)]` parity test
// asserts the two are the same SET, so adding a member on one side only fails
// the build (spec §3 flow 4, §7 edge case 4).
//
// Deliberately a hand-rolled line scanner rather than a TS parser dependency:
// the union is a flat list of quoted literals terminated by `;`, and a parser
// crate would be tier-5 spend for a tier-6 job (minimality ladder).

use std::path::Path;

/// Pull the members of `export type ErrorCode = | 'A' | 'B';` out of a
/// `common.ts` source. Comments are ignored — only quoted SCREAMING_SNAKE
/// literals between the `=` and the terminating `;` count.
fn parse_error_codes(source: &str) -> Vec<String> {
    let mut codes = Vec::new();
    let mut inside = false;
    for line in source.lines() {
        let trimmed = line.trim_start();
        if !inside {
            if trimmed.starts_with("export type ErrorCode") {
                inside = true;
            } else {
                continue;
            }
        }
        // Strip a trailing `// …` comment so a code named inside prose can
        // never be mistaken for a member.
        let code_part = match trimmed.find("//") {
            Some(i) => &trimmed[..i],
            None => trimmed,
        };
        let mut rest = code_part;
        while let Some(open) = rest.find('\'') {
            let after = &rest[open + 1..];
            let Some(close) = after.find('\'') else { break };
            let literal = &after[..close];
            if !literal.is_empty()
                && literal
                    .bytes()
                    .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() || b == b'_')
            {
                codes.push(literal.to_string());
            }
            rest = &after[close + 1..];
        }
        if code_part.trim_end().ends_with(';') {
            break;
        }
    }
    codes
}

fn main() {
    let contract = Path::new("..").join("contract").join("common.ts");
    println!("cargo:rerun-if-changed={}", contract.display());

    let source = std::fs::read_to_string(&contract)
        .unwrap_or_else(|e| panic!("could not read {}: {e}", contract.display()));
    let codes = parse_error_codes(&source);
    assert!(
        !codes.is_empty(),
        "no ErrorCode members found in {} — the union's shape changed and build.rs's scanner \
         needs updating (never work around this by deleting the parity check)",
        contract.display()
    );

    let mut out = String::from(
        "// @generated by build.rs from contract/common.ts — do not edit.\npub const CONTRACT_ERROR_CODES: &[&str] = &[\n",
    );
    for code in &codes {
        out.push_str("    \"");
        out.push_str(code);
        out.push_str("\",\n");
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("contract_error_codes.rs");
    std::fs::write(&dest, out).expect("write contract_error_codes.rs");

    let owns_app_manifest = embed_app_manifest(&out_dir);

    if owns_app_manifest {
        // We supply the manifest for every target below, so tauri must not also
        // compile one into `resource.lib` — two `RT_MANIFEST` id 1 resources in
        // one link is `CVT1100: duplicate resource`.
        tauri_build::try_build(
            tauri_build::Attributes::new()
                .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest()),
        )
        .expect("tauri_build");
    } else {
        tauri_build::build()
    }
}

/// core-architecture-wave3 FR-2: put the Common-Controls v6 manifest on EVERY
/// target, tests included. Returns whether we took ownership of it from tauri.
///
/// The webview/GUI stack imports four comctl32 **v6** symbols —
/// `TaskDialogIndirect`, `SetWindowSubclass`, `RemoveWindowSubclass`,
/// `DefSubclassProc`. `System32\comctl32.dll` is v5.82 and exports none of them;
/// they resolve only through the side-by-side v6 assembly, which a binary opts
/// into with an application manifest. `tauri_build` compiles that manifest into
/// `resource.lib`, which reaches the *bin* targets only — so before FR-2 this
/// was invisible: every test lived in the bin target and inherited it.
///
/// FR-2 moved the modules behind a lib target and the tests went with them, and
/// a lib test harness is its own manifest-less exe. The loader binds v5.82,
/// fails on the first missing entry point, and the process dies with
/// `STATUS_ENTRYPOINT_NOT_FOUND` (0xc0000139) *before* `main` — so `cargo check`
/// stays green while `cargo test` cannot run a single test. That is why this is
/// load-bearing rather than cosmetic: without it FR-2 silently disables the
/// whole suite.
///
/// `rustc-link-arg-tests` would scope a second manifest to tests alone, but it
/// is still unstable, and the stable all-targets `rustc-link-arg` would collide
/// with tauri's copy on the bin (`CVT1100: duplicate resource`). So instead of
/// adding a second manifest we become the ONLY source of it — the content is
/// copied verbatim from `tauri-build`'s own `windows-app-manifest.xml`, so the
/// shipped binary's manifest is unchanged.
fn embed_app_manifest(out_dir: &str) -> bool {
    // MSVC-only: `/MANIFEST:EMBED` is a link.exe flag. Any other toolchain keeps
    // tauri's own handling untouched.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows")
        || std::env::var("CARGO_CFG_TARGET_ENV").as_deref() != Ok("msvc")
    {
        return false;
    }

    // Verbatim `tauri-build/src/windows-app-manifest.xml`. Keep it that way: this
    // is the app's real manifest now, not a test-only shim.
    const MANIFEST: &str = r#"<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="*"
        publicKeyToken="6595b64144ccf1df"
        language="*"
      />
    </dependentAssembly>
  </dependency>
</assembly>
"#;

    let manifest_path = Path::new(out_dir).join("app.manifest");
    std::fs::write(&manifest_path, MANIFEST).expect("write app.manifest");

    println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
    println!(
        "cargo:rustc-link-arg=/MANIFESTINPUT:{}",
        manifest_path.display()
    );
    true
}

#[cfg(test)]
mod tests {
    use super::parse_error_codes;

    #[test]
    fn reads_members_and_ignores_comments_and_other_unions() {
        let src = "export type Other = | 'NOT_ME';\n\
                   export type ErrorCode =\n\
                   \x20 | 'A_ONE' // mentions 'NOT_A_MEMBER' in prose\n\
                   \x20 | 'B_TWO'\n\
                   \x20 | 'C_THREE';\n\
                   export type After = | 'ALSO_NOT_ME';\n";
        assert_eq!(parse_error_codes(src), vec!["A_ONE", "B_TWO", "C_THREE"]);
    }

    #[test]
    fn stops_at_the_terminating_semicolon() {
        let src = "export type ErrorCode = | 'ONLY';\nexport type Next = | 'NOPE';\n";
        assert_eq!(parse_error_codes(src), vec!["ONLY"]);
    }
}
