#!/usr/bin/env python3
"""PreToolUse gate — generic, profile-driven.

Forces a confirmation prompt (or hard-denies) on dangerous Bash commands,
inspecting the FULL command string so chained forms like
`cd apps/api && node ace migration:run` are caught — something prefix-based
permission rules in settings.json miss.

Patterns come from `.claude/gate-config.json` (generated by /init-pipeline from
the PIPELINE.md `gate` block):

    { "deny": ["node ace migration:fresh", ...],
      "ask":  ["git commit", "git push", "node ace migration:run", ...] }

A pattern matches a command segment when the segment *contains* the pattern
(after normalizing whitespace). `deny` wins over `ask`. If the config is missing
or unreadable, the hook stays silent (exit 0) and lets settings.json decide.

Protocol: reads the PreToolUse payload on stdin; emits a JSON permissionDecision
of "deny" or "ask" on a match; otherwise exits 0 silently.
"""

import json
import os
import re
import subprocess
import sys

SPLIT = re.compile(r"&&|\|\||[;|\n]")
WS = re.compile(r"\s+")


def load_config() -> dict:
    root = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    path = os.path.join(root, ".claude", "gate-config.json")
    empty = {"deny": [], "ask": [], "ask_on_default_branch": [], "default_branch": "main"}
    try:
        with open(path, "r", encoding="utf-8") as fh:
            cfg = json.load(fh)
    except Exception:
        return empty
    return {
        "deny": list(cfg.get("deny", [])),
        "ask": list(cfg.get("ask", [])),
        # Patterns gated ONLY on the default branch — allowed freely on feature branches.
        "ask_on_default_branch": list(cfg.get("ask_on_default_branch", [])),
        "default_branch": cfg.get("default_branch", "main") or "main",
    }


def norm(s: str) -> str:
    return WS.sub(" ", s.strip())


def current_branch():
    """The checked-out branch of CLAUDE_PROJECT_DIR, or None (not a repo / detached / git absent)."""
    root = os.environ.get("CLAUDE_PROJECT_DIR", ".")
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=root, capture_output=True, text=True, timeout=3,
        )
        if out.returncode == 0:
            return out.stdout.strip() or None
    except Exception:
        pass
    return None


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0  # malformed input → don't block

    if payload.get("tool_name") != "Bash":
        return 0

    command = (payload.get("tool_input") or {}).get("command", "") or ""
    cfg = load_config()
    deny, ask, branch_gated = cfg["deny"], cfg["ask"], cfg["ask_on_default_branch"]
    default = cfg["default_branch"]
    if not deny and not ask and not branch_gated:
        return 0

    # Branch-conditional patterns (e.g. git/docker) are gated only on the default branch;
    # on a feature branch they run freely. Unknown branch (no repo / detached / no git) ⇒
    # be conservative and gate. Resolve the branch once, lazily.
    on_default = False
    if branch_gated:
        branch = current_branch()
        on_default = branch is None or branch == default

    for raw in SPLIT.split(command):
        seg = norm(raw)
        if not seg:
            continue
        for pat in deny:
            if norm(pat) in seg:
                return decide("deny", f"`{pat}` is forbidden by the project's PIPELINE.md gate.")
        for pat in ask:
            if norm(pat) in seg:
                return decide("ask", f"`{pat}` is a gated command — confirm first (PIPELINE.md gate).")
        if on_default:
            for pat in branch_gated:
                if norm(pat) in seg:
                    return decide("ask", f"`{pat}` is gated on the default branch `{default}` — confirm "
                                         f"(PIPELINE.md gate). It runs freely on feature branches.")

    return 0


def decide(decision: str, reason: str) -> int:
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": decision,
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
