//! User-visible native items; private reasoning content never crosses this boundary.
use crate::session::{
    application::{RuntimeEvent, TurnContext},
    build_step_detail,
};
use serde_json::{json, Value};
use std::collections::HashMap;

#[derive(Default)]
pub(super) struct Details {
    open: HashMap<String, OpenItem>,
}
struct OpenItem {
    block: String,
    tool: String,
    input: Value,
    started: u64,
}
fn view(item: &Value) -> Option<(&str, String, Value, String)> {
    let text = |key: &str| item[key].as_str().unwrap_or_default().to_string();
    Some(match item["type"].as_str()? {
        "reasoning" => {
            let summary = item["summary"]
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .collect::<Vec<_>>()
                .join("\n");
            (
                "Reasoning",
                "Summary".into(),
                json!({"kind":"summary"}),
                summary,
            )
        }
        "plan" => ("Plan", "Plan".into(), json!({}), text("text")),
        "contextCompaction" => (
            "ContextCompaction",
            "Compact conversation context".into(),
            json!({}),
            "Context compaction".into(),
        ),
        "imageView" => (
            "ViewImage",
            text("path"),
            json!({"path":item["path"]}),
            text("path"),
        ),
        "imageGeneration" => (
            "ImageGeneration",
            text("revisedPrompt"),
            json!({"transparentBackground":item["transparentBackground"]}),
            item["savedPath"]
                .as_str()
                .map(|path| format!("Saved image: {path}"))
                .unwrap_or_else(|| "Image generated by Codex".into()),
        ),
        "collabAgentToolCall" => (
            "Task",
            text("tool"),
            json!({"task":item["prompt"],"model":item["model"],"effort":item["reasoningEffort"]}),
            format!("{}: {}", text("tool"), text("status")),
        ),
        "dynamicToolCall" => (
            "Tool",
            text("tool"),
            json!({"tool":item["tool"],"arguments":item["arguments"]}),
            item["contentItems"]
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(|part| part["text"].as_str())
                .collect::<Vec<_>>()
                .join("\n"),
        ),
        "functionCallOutput" => (
            "Tool",
            text("name"),
            json!({"name":item["name"]}),
            item["output"]
                .as_str()
                .map(String::from)
                .unwrap_or_else(|| item["output"].to_string()),
        ),
        "sleep" => ("Wait", "Waiting".into(), json!({}), "Wait finished".into()),
        "enteredReviewMode" | "exitedReviewMode" => {
            ("Review", text("review"), json!({}), text("review"))
        }
        _ => return None,
    })
}
impl Details {
    pub(super) fn item(
        &mut self,
        item: &Value,
        completed: bool,
        ctx: &TurnContext,
    ) -> Vec<RuntimeEvent> {
        let Some((tool, summary, input, result)) = view(item) else {
            return vec![];
        };
        let Some(id) = item["id"].as_str() else {
            return vec![];
        };
        let mut events = vec![];
        if !self.open.contains_key(id) {
            let block = crate::ids::uuid();
            events.push(RuntimeEvent::ToolStarted {
                block_id: block.clone(),
                tool: tool.into(),
                summary,
            });
            self.open.insert(
                id.into(),
                OpenItem {
                    block,
                    tool: tool.into(),
                    input: input.clone(),
                    started: crate::ids::now_ms(),
                },
            );
        }
        if completed {
            let open = self.open.remove(id).unwrap();
            let failed = matches!(item["status"].as_str(), Some("failed" | "errored"))
                || item["success"] == false
                || item["failure"].is_object();
            let detail = build_step_detail(
                &open.block,
                &open.tool,
                &ctx.cwd,
                &ctx.runtime,
                open.started,
                crate::ids::now_ms(),
                failed,
                None,
                &input,
                &result,
                None,
            );
            events.push(RuntimeEvent::ToolCompleted {
                block_id: open.block,
                meta: if failed { "failed" } else { "done" }.into(),
                detail: Some(detail),
                affects_workspace: false,
            });
        }
        events
    }
    pub(super) fn close(&mut self, ctx: &TurnContext) -> Vec<RuntimeEvent> {
        self.open
            .drain()
            .map(|(_, open)| {
                let detail = build_step_detail(
                    &open.block,
                    &open.tool,
                    &ctx.cwd,
                    &ctx.runtime,
                    open.started,
                    crate::ids::now_ms(),
                    true,
                    None,
                    &open.input,
                    "Interrupted before completion",
                    None,
                );
                RuntimeEvent::ToolCompleted {
                    block_id: open.block,
                    meta: "interrupted".into(),
                    detail: Some(detail),
                    affects_workspace: false,
                }
            })
            .collect()
    }
}
